export const FETCH_STORY_REQUEST = 'FETCH_STORY_REQUEST';
export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_SINGLE_STORY = 'FETCH_SINGLE_STORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SIDEBAR_TOP_FOUR = 'FETCH_SIDEBAR_TOP_FOUR';
export const FETCH_SIDEBAR_RANDOM = 'FETCH_SIDEBAR_RANDOM';